name: CI
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: checkout project
        uses: actions/checkout@v2
      - name: Roave Security advisories
        run: composer require --dev roave/security-advisories:dev-latest
      - name: The PHP Security Checker
        uses: symfonycorp/security-checker-action@v2
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout project
        uses: actions/checkout@v2
      - name: Setup composer
        run:  composer install --prefer-dist --no-progress --no-suggest
      - name: run static analysis
        run:  composer static-analysis
